[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "5000"

[build.watchPatterns]
includes = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.json"]
excludes = ["node_modules/**", "dist/**", ".git/**", "*.log"]

[healthcheck]
path = "/api/bot/status"
port = 5000
initialDelaySeconds = 30
periodSeconds = 10
timeoutSeconds = 5
failureThreshold = 3

[networking]
allowedHosts = [
  "api.telegram.org",
  "*.googleapis.com",
  "*.neon.tech"
]

# Database will be automatically detected and linked by Railway